CXX=g++
CXXFLAGS=-std=c++17 -Wall -fsanitize=address,leak -g
LDFLAGS=-fsanitize=address,leak

.PHONY: all clean

all: l6

l6:
# TODO: Add the object files to the target
l6: main.cpp Cargoes.cpp Transport.cpp
	$(CXX) -o l6 main.cpp Cargoes.cpp Transport.cpp

clean:
	rm -f *.o l6